spring.application.name=Shoe_Store_App
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.jpa.hibernate.ddl-auto=validate
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
frontend.url=${FRONTEND_URL}
brevo.api.key=${BREVO_API_KEY}
mail.from=${MAIL_FROM}
springdoc.show-actuator=true
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
server.forward-headers-strategy=framework
