spring.datasource.url=jdbc:postgresql://localhost:5432/shoe_store
spring.datasource.username=admin
spring.datasource.password=password
spring.docker.compose.enabled=false
spring.liquibase.enabled=false
